### ISSUE TITLE
[Umbrella] Tests Requirements

### ISSUE THREAD

**Issue by waitinfuture** [apache/incubator-celeborn#924]
### This issue tracks integration tests(IT) or unit tests(UT) to be added
- [ ] IT: reserve slots fail randomly to test retryReserveSlots
- [ ] IT: Graceful shutdown while running test suite
- [ ] IT: Rolling upgrade Masters && Workers while running test suite
- [ ] IT: Create file error, flush error, disk usage full, disk un-writable
- [ ] IT: Trigger shuffle read retry
- [ ] IT: Some application timeout while others running
- [ ] IT: Pressure tests
- [ ] IT: K8S regression
- [ ] IT: HDFS regression
